### ISSUE TITLE
On browser startup, if you're fast you can access a site before addon initializes

### ISSUE THREAD

**Issue by tuurep** [AsciiJakob/NoDistractions#9]
If addon is supposed to be enabled on startup, it takes something like ~1 second to initialize.

For some people this can be a non-issue, but I habitually launch a browser and immediately go to a site in a way that's always faster than the initialize time.

**Comment by AsciiJakob** [comment]
I have an idea for a way to fix this and will try it out today if I have the time

**Comment by AsciiJakob** [comment]
Two issues have now been fixed:
1. The problem you described
2. If the last page focused after starting firefox with persistent tabs enabled is in the blocklist it gets blocked.

Fixing this was very hacky. I have to rely on a settimeout in order for my check to compensate for the amount of time it takes for the webrequest listener to get started. But whatever, it works. Perhaps you want to verify that it is fixed?

**Comment by tuurep** [comment]
Yeah this works great! Was there anything else here or should we close this? :)

**Comment by AsciiJakob** [comment]
All done. Cheers for submitting the issue

**Comment by tuurep** [comment]
Reminder: we found out that depending on site, issue may still occur (which is strange)

Doesn't happen with reddit, but still happens with youtube.

Should we reopen this?

**Comment by AsciiJakob** [comment]
Yep. I'm gonna have to investigate this, fix should be included in the next release but I don't think it's worth making a patch just for this bug
